mysite/myapp/urls.py
from django.urls import path
from myapp.views import index,indexItem, add_item, update_item, delete_item

app_name = "myapp"

urlpatterns = [
  #Это url самого приложения app,если в первом параметре указать значение, например "hello", то оно будет всегда идти после главного "myapp", главные url находятся в mysite/mysite/urls

  # http://127.0.0.1:8000/myapp/hello
  path('', index, name='index'),
  path('<int:my_id>/', indexItem, name="detail"),
  # http://127.0.0.1:8000/myapp/contacts
  path('additem/', add_item, name="add_item"),
  path('updateitem/<int:my_id>/', update_item, name="update_item"),
  path('deleteitem/<int:my_id>/', delete_item, name="delete_item"),
  
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # http://127.0.0.1:8000/hello/
    #главные url 
    path('myapp/', include("myapp.urls", namespace="myapp")),
    path('users/', include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register, profile
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from .views import seller_profile



app_name = "users"

urlpatterns = [
  #Это url самого приложения app,если в первом параметре указать значение, например "hello", то оно будет всегда идти после главного "myapp", главные url находятся в mysite/mysite/urls

  # http://127.0.0.1:8000/myapp/hello
  path('register/', register, name='register'),
  path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
  path("logout/", views.logout_view, name="logout"),
  path("profile/", profile, name="profile"),
  path("sellerprofile/<int:id>", seller_profile, name="sellerprofile"),
  # path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
  
  
]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Product(models.Model):
  seller = models.ForeignKey(User, on_delete=models.CASCADE,default='1')
  name = models.CharField(max_length=100)
  price = models.IntegerField(blank=False, null=True)
  description = models.CharField(max_length=400,null=True)
  image = models.ImageField(blank=True, upload_to="images")

  def __str__(self):
    return self.name

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  image = models.ImageField(blank=True, upload_to='_profile_images')
  contact_number = models.CharField(max_length=50, default= "+78543672312" )

  def __str__(self):
    return self.user.username

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
  email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'focus:outline-none', 'placeholder': 'mail@mail.com'}))
  username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'focus:outline-none', 'placeholder': 'Enter username...'}))
  password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'focus:outline-none', 'placeholder': 'Enter password'}))
  password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'focus:outline-none', 'placeholder': 'Enter same password'}))

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

  # def save(self, commit=True):
  #   user = super(NewUserForm,self).save(commit=False)
  #   user.email = self.cleaned_date['email']
  #   if commit:
  #     user.save()
  #   return user

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def index(request):
	items= Product.objects.all()
	context = {
		'items' : items,
  }
	return render(request, "myapp/index.html", context)

def indexItem(request, my_id):
	item = Product.objects.get(id=my_id) 
	context = {
		'item' : item,
  }
	return render(request, "myapp/detail.html",context=context )


@login_required
def add_item(request):
	if request.method == 'POST':
		name = request.POST.get("name")
		price = request.POST.get("price")	
		description = request.POST.get("description")
		image = request.FILES['upload']
		seller = request.user
		item = Product(name=name, price=price, description=description, image=image, seller=seller)
		item.save()
	return render(request, 'myapp/additem.html')

def update_item(request, my_id):
	item = Product.objects.get(id=my_id) 
	if request.method == 'POST':
		item.name = request.POST.get("name")
		item.price = request.POST.get("price")	
		item.description = request.POST.get("description")
		item.image = request.FILES.get('upload',item.image )
		item.save()
		return redirect("/myapp/")
	context = {
		'item' : item,
  }
	return render(request, 'myapp/updateitem.html', context)


def delete_item(request, my_id):
	item = Product.objects.get(id=my_id) 
	if request.method == 'POST':
		item.delete()
		return redirect("/myapp/")
	context = {
		'item' : item,
  }
	return render(request, 'myapp/deleteitem.html', context)

# def logout_view(request):
#     logout(request)
#     messages.success(request, "Вы успешно вышли из системы.")
#     return render(request, "users/login.html")

mysite/users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        print("form is valid:", form.is_valid()) #Отладочный вывод
        if form.is_valid():
            user = form.save()
            print("User saved:", user) #Отладочный вывод
            messages.success(request, "Registration successful!")
        else:
            print(form.errors) #Отладочный вывод - покажет ошибки валидации
            messages.error(request, "Registration failed. Please correct the errors below.")
    else:
        form = NewUserForm()
    context = {"form": form}
    return render(request, "users/register.html", context)
# Create your views here.

# from .forms import NewUserForm
# from django.shortcuts import render

# def register(request):
#     if request.method == "POST":
#         form = NewUserForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#     form = NewUserForm()
#     context = {"form": form}
#     return render(request, "users/register.html", context)

def logout_view(request):
    logout(request)
    messages.success(request, "Вы успешно вышли из системы.")
    return render(request, "users/login.html")

@login_required
def profile(request):
    return render(request, 'users/profile.html')


def seller_profile(request, id):
    seller = User.objects.get(id=id)

    context = {
        'seller': seller
    }

    return render(request, 'users/sellerprofile.html', context)

mysite/myapp/templates/myapp/additem.html
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="text" placeholder="Name..." name="name" id="name" id="name" />
	<input type="text" placeholder="Price..." name="name" id="price" id="price" />
	<input
		type="text"
		placeholder="Description..."
		name="name"
		id="description"
	/>
	<input type="file" accept="image/*" name="upload" id="upload" />
	<button type="submit" name="Add Item" value="Add Item">Add Item</button>
</form>

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<script src="https://unpkg.com/@tailwindcss/browser@4"></script>

		<title>Document</title>
	</head>
	<body>
		{% include "myapp/navbar.html" %} {% block content %} {% endblock content %}
	</body>
</html>

mysite/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %} {% block content %}
<h1>Delete Product</h1>
<form method="post">
	{% csrf_token %}
	<div>
		<label for="">Are you sure to delete {{item.name}}</label>
		<img class="w-40 h-40" src="{{ item.image.url }}" />
	</div>
	<input
		class="bg-red-500 text-white px-5 py-2"
		type="submit"
		value="Confirm"
	/>
	<a href="{% url 'myapp:index' %}">Cancel</a>
</form>
{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %} {% load humanize %} {% block content %}
<div class="flex p-10 w-full h-200">
	<img class="w-1/3" src="{{item.image.url}}" alt="itemPhoto" />
	<div class="w-2-3 text-xl ml-10 mt-10">
		<p class="mt-5">{{ item.name}}</p>
		<p class="mt-5 text-green-500">$ {{ item.price | intcomma}}</p>
		<p class="mt-5 text-gray-600">{{ item.description}}</p>
		<p class="mt-5 text-purple-400"> <a href="{% url 'users:sellerprofile' item.seller.id %}">@ {{ item.seller}}</a></p>
		<p class="mt-5 text-green-400">{{ item.seller.profile.contact_number}}</p>
		<button class="bg-green-500 text-white mt-[50px]">
			<a href="{% url 'myapp:update_item' item.id %}">Update Item</a>
		</button>
		<button class="bg-red-500 text-white mt-[50px]">
			<a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a>
		</button>
	</div>
</div>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %} {% block content %}

<main
	class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28"
>
	<div class="sm:text-center lg:text-left">
		<h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-5xl">
			<span class="xl:inline">Эсклюзивные товары</span>
			<span class="xl:inline text-green-500">По Супер Ценам</span>
		</h1>
		<p
			class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"
		>
			Вы можете заказать товар из любой точки мира. Доставка включена
		</p>
	</div>

	<div
		class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-5"
	>
		<!-- <a href="/myapp/items/{{item.id}}/"></a> -->
		{% for item in items %}
		<a href="{% url 'myapp:detail' item.id %}">
			<div class="rounded overflow-hidden shadow-lg">
				<img class="w-full h-[400px]" src="{{item.image.url}}" alt="" />
				<div class="px-6 py-4">
					<p class="font-bold text-xl mb-2">{{item.name}}</p>
					<p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
					<p class="font-bold text-xl text-indigo-500 mb-2">by: {{item.seller}}</p>
					<p class="text-gray-700 text-base">{{ item.description}}</p>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</main>
{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
	<div class="max-w-6xl mx-auto px-4">
		<div class="flex justify-between">
			<div class="flex space-x-7">
				<div>
					<a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
						<img
							class="h-8 w-8"
							src="{% static 'myapp/images/store.png' %}"
							alt="logo-image"
						/>
						<span class="text-gray-500 font-semibold text-xl"
							>Professional shop</span
						>
					</a>
				</div>
				<div class="items-center flex space-x-1">
					<a
						href="{% url 'myapp:index' %}"
						class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500"
						>Home</a
					>
					<a href="{% url 'myapp:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
					<a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
					{% if user.is_authenticated %}
						<a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
						<a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
						{% else %}
						<a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
					{% endif %}
					</form>
				</div>
			</div>
		</div>
	</div>
</nav>

mysite/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %} {% block content %}
<div class="ml-[200px]">
	<h1 class="text-2xl m-10 font-bold text-green-600">Update New Item</h1>
	<form
		class="w-1/3 bg-white shadow-md m-10 px-8 py-8"
		method="post"
		enctype="multipart/form-data"
	>
		{% csrf_token %}
		<div class="mb-4">
			<label class="block text-gray-700 text-md font-bold mb-2" for="name"
				>Item Name</label
			>
			<input
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
				value="{{ item.name }}"
				type="text"
				placeholder="Name..."
				name="name"
				id="name"
			/>
			<label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price"
				>Item Price</label
			>
			<input
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
				value="{{ item.price }}"
				type="text"
				placeholder="Price..."
				name="price"
				id="price"
			/>
			<label
				class="block text-gray-700 text-md font-bold mb-2 mt-2"
				for="description"
				>Item Description</label
			>
			<input
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
				value="{{ item.description }}"
				type="text"
				placeholder="Description..."
				name="description"
				id="description"
			/>
			<img class="w-20 h-20" src="{{ item.image.url}}" alt="" srcset="" />
			<input
				class="block mt-4"
				type="file"
				accept="image/*"
				name="upload"
				id="upload"
			/>
			<button
				class="block bg-green-600 text-white p-3 mt-4"
				type="submit"
				name="Add Item"
				value="Add Item"
			>
				Update Item
			</button>
		</div>
	</form>
</div>

{% endblock content %}

mysite/users/templates/users/login.html
{% extends "myapp/base.html" %} {% block content %}
<div class="container py-5">
	<h1 class="text-2xl m-10 font-bold">Login User</h1>
	<form
		class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4"
		method="post"
	>
		{% csrf_token %}
		<div class="mb-2">
			<label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.username}}
			</p>
			<label class="block text-gray-700 text-sm font-bold mt-5 mb-2"
				>Password</label
			>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.password}}
			</p>
		</div>
		<button class="bg-green-500 text-white px-5 py-2" type="submit">
			Login
		</button>
		<button class="bg-sky-600 text-white px-5 py-2">
			<a href="{% url 'users:register' %}">Register?</a>
		</button>
	</form>
</div>
{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "myapp/base.html" %} 
{% block content %}
<h1>You have been logout</h1>
{% endblock content %}

mysite/users/templates/users/profile.html
{% extends "myapp/base.html" %}
{% comment %} {% extends "myapp/base.html" %} 
{% block content %}

  {% if user.profile %}
  <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
      <div>
        {% if user.profile.image %}
        <img width="300" src="{{ user.profile.image.url }}">
        {% endif %}
      </div>
      <h1>{{ user.username }}</h1>
    </div>
  </div>

  {% else %}

  <form action="" method="post">
  <h1>FORM Profile</h1>
  </form>
  {% endif %}
  
{% endblock content %} {% endcomment %}



{% block content %}

    {% if user.profile %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div>
                {% if  user.profile.image %}
                    <img src="{{ user.profile.image.url }}">
                {% endif %}
                
            </div>
            <h1 class="font-bold text-xl m-2">{{ user.username }}</h1>
        </div>
    </div>
    {% else %}
    <div class="container py-5">
        <h1 class="text-2xl m-10 font-bold">Register User</h1>
        <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2">Upload profile image </label>
                <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload" required>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Contact number</label>
                <input class="block mt-4" type="text"  name="number" id="number">
            </div>
            <button class="bg-green-500 text-white px-5 py-2" type="submit">Create Profile</button>
        </form>
    </div>
    {% endif %}
   
{% endblock content %}

mysite/users/templates/users/register.html
{% extends "myapp/base.html" %} {% block content %}
<div class="container py-5">
	<h1 class="text-2xl m-10 font-bold">Register User</h1>
	<form
		class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4"
		method="post"
	>
		{% csrf_token %}
		<div class="mb-2">
			<label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.username}}
			</p>
			<label class="block text-gray-700 text-sm font-bold mt-5 mb-2"
				>Email</label
			>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.email}}
			</p>
			<label class="block text-gray-700 text-sm font-bold mt-5 mb-2"
				>Password</label
			>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.password1}}
			</p>
			<label class="block text-gray-700 text-sm font-bold mt-5 mb-2"
				>Confirm Password</label
			>
			<p
				class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight"
			>
				{{form.password2}}
			</p>
		</div>
		<button class="bg-green-500 text-white px-5 py-2" type="submit">
			Register
		</button>
	</form>
</div>

{% endblock content %}

mysite/users/templates/users/sellerprofile.html
{% extends "myapp/base.html" %} 
{% block content %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div>
                {% if  seller.profile.image %}
                    <img src="{{ user.profile.image.url }}">
                {% endif %}
                
            </div>
            <h1 class="font-bold text-xl m-2">{{ seller.username }}</h1>
        </div>
    </div>
{% endblock content %}